const express = require('express')
const homeController = require('../controller/home.controller')
const authController = require('../controller/auth.controller')
const middleware = require('../../middleware/index.middleware')
const multer  = require('multer')
const upload = multer({ dest: 'public/uploads/' })
const router = express.Router()

router.get('/', middleware.isLogin, homeController.home)
router.get('/chat', middleware.checkAuth, homeController.chat)
router.get('/video-call/:idRoom', middleware.checkAuth, middleware.checkUserInRoom, homeController.videoCall)
router.get('/chat/:idroom', middleware.checkAuth, homeController.chat)
router.post('/change-name', middleware.checkAuth, homeController.changeNameThreadChat)
router.post('/appoint-admin-group', middleware.checkAuth, homeController.appointGroupAdmin)
router.post('/create-or-add-chat-list-personal', middleware.checkAuth, homeController.createOrAddChatListPersonal)
router.post('/add-users-to-groups', middleware.checkAuth, homeController.addUsersToGroups)
router.post('/hide-chat-list', middleware.checkAuth, homeController.hideChatList)
router.post('/kick-out-group', middleware.checkAuth, homeController.kickOutGroup)
router.post('/create-group-chat', middleware.checkAuth, homeController.createGroupChat)
router.post('/send-message', middleware.checkAuth, homeController.sendMessage)
router.post('/add-chat-list-group', middleware.checkAuth, homeController.addChatListGroup)

module.exports = router
